spring:
  application:
    name: accounts

#  config:
#    import:
#      - "accounts-qa.yml"
#      - "accounts-prod.yml"
#  profiles:
#    active: "qa"


build:
  version: "3.0"


accounts:
  message: "Welcome to EazyBank accounts related WebHook APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
      - (555) 523-1345

