server:
  port: 8090
spring:
  application:
    name: "loans"

build:
  version: "3.0"

loans:
  message: "Welcome to EazyBank loans related local APIs "
  contactDetails:
    name: "Amaal Grega - Developer"
    email: "{cipher}c386c492bff1fa5db46071de5f8efa7943126997510cfe938d938c21de5ba69511c09b3a45e0dda28a3bc40c709613b7"
  onCallSupport:
      - (452) 456-2176
      - (546) 764-8934
